apiVersion: v1
kind: ConfigMap
metadata:
  name: visual-app-interface
data:
  env: |
    window.DATA_DIR_URL = 'PLACEHOLDER_OVERRIDE_IN_OVERLAY';
    window.DOCS_BASE_URL = 'PLACEHOLDER_OVERRIDE_IN_OVERLAY';
    window.SCHEMAS_DIR = 'PLACEHOLDER_OVERRIDE_IN_OVERLAY';
    window.GF_ROOT_URL = 'PLACEHOLDER_OVERRIDE_IN_OVERLAY';
    window.QONTRACT_API_URL = 'PLACEHOLDER_OVERRIDE_IN_OVERLAY';
    window.ACS_URL = 'PLACEHOLDER_OVERRIDE_IN_OVERLAY';
  # These values must be overridden in environment overlays (e.g., app-sre-cd/visual-app-interface/overlays/*/configmap-patch.yaml)
  graphql.uri: 'PLACEHOLDER_OVERRIDE_IN_OVERLAY'
  api.uri: 'PLACEHOLDER_OVERRIDE_IN_OVERLAY'
